version: '3.1'
services:
  springboot:
    image: ragavandockeraccount/dockercomposefile:$buildNumber
    restart: always
    ports:
    - 9000:8080
    networks:
    - mavenappbridge
networks:
  mavenappbridge:
